[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
script = 'script'

# Test settings
fuzz = { runs = 1000 }  # More thorough fuzzing than default
gas_reports = ["*"]     # Generate gas reports for all contracts

[fmt]
number_underscore = "thousands"
wrap_comments = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }